### ISSUE TITLE
Add some simple tests

### ISSUE THREAD

**Issue by darsnack** [darsnack/FluxModels.jl#5]
It is hard to test this package, because we don't want to run training on the CI. But, a simple test can be passing through a random tensor and ensuring the output size is the expected size. Here is an example:
```
m = alexnet()
@test size(m(rand(256, 256, 3, 50))) == (1000, 50)
```

We would add such tests for every model configuration. This ensures that the models can at least do a forward pass with no errors.

**Comment by a-r-n-o-l-d** [comment]
I will write these tests for VGG models as soon as possible (I need to clearly understand Julia unit testing API).

**Comment by darsnack** [comment]
Hi @arnold-dev I really appreciate your contributions. But the issues that I am filing in this repo are currently intended for an MLH student. In this case, @dnabanita7 is already working on this issue. Once the MLH fellowship period is over, there will still be work to do in this repo, and I'd welcome your contributions then.

In the meantime, I'd recommend taking a look at [the ML ecosystem issue tracker](https://github.com/JuliaCommunity/ML-Coordination-Tracker) or [FastAI.jl](https://github.com/opus111/FastAI.jl) if you are looking for active issues to contribute to.

**Comment by dnabanita7** [comment]
Can you please assign me this issue?

**Comment by a-r-n-o-l-d** [comment]
Hi @darsnack, sure, I understand, sorry about that. I will have a look at the ML ecosystem issue tracker. I have a lot of code to share (lot of time during confinement), in the meantime, I will put it on my github and it could be incorporated later.

**Comment by darsnack** [comment]
Awesome, we would really love for you to share that code when you are ready.
